---
- name: update Unbuntu repository and distros
  hosts: ubuntu
  become: yes
  tasks:
    - name: update package repository
      apt: 
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: update all packages
      apt: 
        upgrade=dist
      when: ansible_os_family == "Debian"